### ISSUE TITLE
needs a short lab

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/reading-ios-creatingMethods#6]
^^

@markedwardmurray

**Comment by AnnJohn** [comment]
Iceboxing for now. @markedwardmurray close when you're done with the issue.

**Comment by AnnJohn** [comment]
Iceboxing for now @markedwardmurray feel free to close when you're done with the issue

**Comment by markedwardmurray** [comment]
resolved by https://github.com/learn-co-curriculum/objc-palindrome-detector/pull/1
